# Makefile for pcf2bdf (Visual C++ 5.0)  -*- makefile -*-

CXX		= cl
CXXFLAGS	= /O2
RM		= del

all:		pcf2bdf

pcf2bdf:	pcf2bdf.cc
	$(CXX) $(CXXFLAGS) /Tppcf2bdf.cc

clean:
	-$(RM) pcf2bdf pcf2bdf.exe pcf2bdf.obj *~
